version: '3.8'

services:
  api-gateway:
    image: afsapp.azurecr.io/test-api:v1
    ports:
      - "5000:5000"
    networks:
      - backend

  auth:
    image: afsapp.azurecr.io/test-auth:v1
    networks:
      - backend

  confined-space:
    image: afsapp.azurecr.io/test-confi:v1
    networks:
      - backend

  location-service:
    image: afsapp.azurecr.io/test-loca:v1
    networks:
      - backend

  client:
    image: afsapp.azurecr.io/test-front:v1
    ports:
      - "8080:80"
    depends_on:
      - api-gateway
      - auth
      - confined-space
      - location-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
